version: '3.5'

services:
  koga-wash-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - koga-wash-db
    volumes:
      - .env:/usr/src/koga-wash/.env
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_HOST: koga-wash-db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: koga_wash

  koga-wash-db:
    image: mysql
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: koga_wash
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    name: koga-wash
