apiVersion: apps/v1
kind: Deployment
metadata:
  name: koga-wash-frontend
spec:
  selector:
    matchLabels:
      app: koga-wash-frontend
  template:
    metadata:
      labels:
        app: koga-wash-frontend
    spec:
      containers:
        - image: haginus/koga-wash-frontend
          name: koga-wash-frontend
          ports:
            - containerPort: 80